# Generated by Django 4.1.4 on 2023-01-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
